github:
  organisations:
  - name: jenkins-x
    repositories:
    - name: builder-base
      excludeUpdateLoop: true
    - name: homebrew-jx
    - name: jx-docs
    - name: jenkins-x-platform
    - name: jx-tutorial
