# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/code-generator/cmd/client-gen"
]

[[constraint]]
  branch = "master"
  name = "code.gitea.io/sdk"

[[constraint]]
  name = "github.com/Jeffail/gabs"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/MakeNowJust/heredoc"

[[constraint]]
  branch = "master"
  name = "github.com/Pallinder/go-randomdata"

[[constraint]]
  name = "github.com/beevik/etree"
  version = "1.0.1"

[[constraint]]
  name = "github.com/blang/semver"
	version = "=v3.5.1"

[[constraint]]
  name = "github.com/chromedp/chromedp"
  version = "=v0.1.1"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
	version = "v18.0.0"
  name = "github.com/google/go-github"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-version"

[[constraint]]
  branch = "master"
  name = "github.com/jenkins-x/chyle"

[[constraint]]
  branch = "copy-pack-contents"
  name = "github.com/jenkins-x/draft-repo"
  source = "https://github.com/jenkins-x/old-draft-repo.git"

[[constraint]]
  branch = "master"
  name = "github.com/jenkins-x/golang-jenkins"

[[constraint]]
  branch = "master"
  name = "github.com/nlopes/slack"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/browser"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/wbrefvem/go-bitbucket"

[[constraint]]
  branch = "master"
  name = "github.com/xanzy/go-gitlab"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.5.2"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.1.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "k8s.io/helm"
  source = "https://github.com/jenkins-x/helm.git"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.18"

[[constraint]]
  name = "github.com/heptio/sonobuoy"
  branch = "master"

[[constraint]]
  name = "github.com/alexflint/go-filemutex"
  branch = "master"
  source = "https://github.com/i0n/go-filemutex.git"

[[constraint]]
  name = "k8s.io/test-infra"
  branch = "release-1.11"
  source = "https://github.com/jenkins-x/test-infra.git"

[[constraint]]
  name = "github.com/knative/build"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    non-go = false
    go-tests = false


[[constraint]]
  name = "github.com/andygrunwald/go-gerrit"
  version = "0.5.2"

[[constraint]]
  branch = "master"
  name = "github.com/denormal/go-gitignore"

[[constraint]]
  name = "github.com/codeship/codeship-go"
  version = "0.3.1"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.0.0"

[[constraint]]
  name = "github.com/bouk/monkey"
  branch = "master"
  source = "github.com/i0n/monkey"
