apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  creationTimestamp: null
  name: add-common-envvars
spec:
  steps:
  - args:
    - mvn
    - test
    env:
    - name: CHEESE
      value: Edam
    image: jenkinsxio/builder-maven:0.0.408
    name: run-tests
    resources: {}
  - args:
    - mvn
    - deploy
    env:
    - name: CHEESE
      value: ShouldNotBeOverwritten
    image: jenkinsxio/builder-maven:0.0.408
    name: deploy
    resources: {}
status:
  completionTime: null
  startTime: null
  stepStates: null
  stepsCompleted: null
