controller-role:
  serviceaccount:
    enabled: true
  deployment:
    enabled: true
  args:
  - "controller"
  - "role"
  role:
    enabled: true
    rules:
    - apiGroups:
      - jenkins.io
      resources:
      - environmentrolebindings
      verbs:
      - list
      - get
      - watch
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - list
      - watch
      - get