controller-team:
  serviceaccount:
    enabled: true
  deployment:
    enabled: true
  args:
  - "controller"
  - "team"
  - "--install-dependencies"
  role:
    enabled: true
    rules:
    - apiGroups:
      - jenkins.io
      resources:
      - teams
      verbs:
      - list
      - get
      - watch
