gc-releases:
  serviceaccount:
    enabled: true
  cronjob:
    enabled: true
    schedule: "0/30 */3 * * *"
  args:
  - "gc"
  - "releases"
  role:
    enabled: true
    rules:
    - apiGroups:
      - jenkins.io
      resources:
      - releases
      verbs:
      - list
      - delete
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - list
      - get