compliance-role:
  serviceaccount:
    enabled: true
  deployment:
    enabled: true
  args:
  - "compliance"
  - "role"
  role:
    enabled: true
    rules:
    - apiGroups:
      - jenkins.io
      resources:
        compliancechecks
      verbs:
      - get
      - create
      - update
      - watch
    - apiGroups:
      - jenkins.io
      resources:
        pipelineactivities
      verbs:
      - get
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - watch