controller-workflow:
  serviceaccount:
    enabled: true
  deployment:
    enabled: true
  args:
  - "controller"
  - "workflow"
  role:
    enabled: true
    rules:
    - apiGroups:
      - jenkins.io
      resources:
      - pipelineactivities
      verbs:
      - list
      - get
      - watch
      - create
      - update
    - apiGroups:
      - jenkins.io
      resources:
      - workflows
      verbs:
      - list
      - get
      - watch
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - list
      - get