apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  creationTimestamp: null
  name: default-image-from-previous-step
spec:
  steps:
  - args:
    - mvn
    - test
    image: jenkinsxio/builder-maven:0.0.408
    name: run-tests
    resources: {}
  - args:
    - mvn
    - test
    image: jenkinsxio/builder-maven:0.0.408
    name: deploy
    resources: {}
status:
  completionTime: null
  startTime: null
  stepStates: null
  stepsCompleted: null
