controller-build:
  serviceaccount:
    enabled: true
  deployment:
    enabled: true
  args:
  - "controller"
  - "build"
  role:
    enabled: true
    rules:
    - apiGroups:
      - jenkins.io
      resources:
      - pipelineactivities
      verbs:
      - list
      - get
      - watch
      - create
      - update
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - list
      - watch
      - get
